# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=200)),
                ('secret', models.CharField(max_length=200)),
                ('role', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='AdminRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentDownloads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('contenturl', models.TextField(default='')),
                ('previewurl', models.TextField(default='')),
                ('image', models.TextField(default='')),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tid', models.IntegerField(default=0)),
                ('paymenttref', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=2000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('contenturl', models.TextField(default='')),
                ('previewurl', models.TextField(default='')),
                ('image', models.TextField(default='')),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadTransactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('documentid', models.IntegerField(default=0)),
                ('downloadattempts', models.IntegerField(default=0)),
                ('uid', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(max_length=1000)),
                ('otherref', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=20)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=20)),
                ('voucher_code', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='DownloadUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cartid', models.CharField(max_length=200)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('address1', models.CharField(max_length=500)),
                ('address2', models.CharField(max_length=500)),
                ('town', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('packageinfo', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
                ('uid', models.IntegerField(default=0)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('description', models.CharField(max_length=1000)),
                ('otherref', models.CharField(max_length=100)),
                ('reference', models.CharField(max_length=100)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=20)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=20)),
                ('voucher_code', models.CharField(max_length=20)),
                ('status', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
