# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=25)),
                ('skype', models.CharField(max_length=200)),
                ('facetime', models.CharField(max_length=200)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('city', models.IntegerField(default=0)),
                ('city_other', models.CharField(max_length=200)),
                ('state', models.IntegerField(default=0)),
                ('state_other', models.CharField(max_length=200)),
                ('town', models.IntegerField(default=0)),
                ('town_other', models.CharField(max_length=200)),
                ('country', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=500)),
                ('secret', models.CharField(max_length=500)),
                ('status', models.IntegerField(default=0)),
                ('is2faverified', models.IntegerField(default=0)),
                ('isemailverified', models.IntegerField(default=0)),
                ('role', models.IntegerField(default=0)),
                ('createdate', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('packageid', models.IntegerField(default=0)),
                ('uid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccessList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('accesstype', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroupList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('groupid', models.IntegerField(default=0)),
                ('uid', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserValidity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField(default=0)),
                ('lastrenewdate', models.DateTimeField(verbose_name='')),
                ('nextrenewdate', models.DateTimeField(verbose_name='')),
            ],
        ),
    ]
