# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-14 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_profile_user_useraccess_useraccesslist_usergroup_usergrouplist_userrole_uservalidity'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadusers',
            name='otherref',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='downloadusers',
            name='reference',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
